package com.example.runtracker2.other

object Constants {
    const val RUN_DATABASE_NAME = "run_db"
    const val REQUEST_CODE_LOCATION_PERMISSION = 0
    const val REQUEST_CODE_NOTIFICATION_PERMISSION = 0


    const val ACTION_START_OR_RESUME_SERVICE = "ACTION_START_OR_RESUME_SERVICE"
    const val ACTION_PAUSE_SERVICE = "ACTION_PAUSE_SERVICE"
    const val ACTION_STOP_SERVICE = "ACTION_STOP_SERVICE"

    const val ACTION_SHOW_TRACKING_SCREEN = "ACTION_SHOW_TRACKING_SCREEN"


    const val NOTIFICATION_CHANNEL_ID = "tracking_channel"
    const val NOTIFICATION_CHANNEL_NAME = "Tracking"
    const val NOTIFICATION_ID = 1

    const val LOCATION_UPDATE_INTERVAL = 5000L
    const val FASTEST_LOCATION_INTERVAL = 2000L

    const val TIMER_UPDATE_INTERVAL = 50L

    const val SORTED_BY_DATE = "SORTED_BY_DATE"
    const val SORTED_BY_TIME_IN_MILLIS = "SORTED_BY_TIME_IN_MILLIS"
    const val SORTED_BY_CALORIES_BURNED = "SORTED_BY_CALORIES_BURNED"
    const val SORTED_BY_AVG_SPEED = "SORTED_BY_AVG_SPEED"
    const val SORTED_BY_DISTANCE = "SORTED_BY_DISTANCE"

    const val SHARED_PREFERENCES_NAME = "sharedPref"
    const val KEY_FIRST_TIME_TOGGLE = "KEY_FIRST_TIME_TOGGLE"
    const val KEY_NAME = "KEY_NAME"
    const val KEY_WEIGHT = "KEY_WEIGHT"
}